name: Node.js CI

on: [push]						# workflow runs on a git push

jobs:
  build:						# workflow has one job: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4		# checks out code for runner
      - name: Use Node.js
        uses: actions/setup-node@v4		# uses Action from marketplace
        with:
          node-version: '19.10'
      - run: npm ci				# executes several 
      - run: npm run build --if-presnet  # a simple typo error
      - run: npm test
